### ISSUE TITLE
分享文字失败，响应状态码500

### ISSUE THREAD

**Issue by lirtual** [xiadd/pastebin-worker#13]
分享文件没问题，但是分享文字用不了，看请求响应的是500，文字用的是kv吧，但是我有配置好kv的，放出wrangler.toml帮我看看有没什么问题？

另外：BASE_URL和自定义域名我在worker后台配置的。

![image](https://github.com/user-attachments/assets/62eb4413-6d17-49f5-af3d-90457fcd43ad)

```toml
name = "pastebin"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

account_id = "950264872e4a996635e310b837126911"
main = "src/index.ts"
workers_dev = false

# 如果不使用自定义域名，将下面的代码注释掉
# route = { pattern = "as.al", custom_domain = true }

kv_namespaces = [
  { binding = "pastebin", id = "4b6a65b267d644749354f2a318c1677b" },
]

[vars]
ENVIRONMENT = "production"
BASE_URL = "https://as.al"

[site]
bucket = "./static/dist"


[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'pastes'

# [[d1_databases]]
# binding = "DB"
# database_name = "pastebins"
# database_id = "e7d77803-c383-45c8-9481-c1630aa43bca"```

**Comment by dolacmeo** [comment]
kv_namespaces 没用了，最新的commits已经去掉了
现在数据存在D1里面。
教程也没更新，缺少了对D1设置的说明
https://github.com/xiadd/pastebin-worker/blob/953d1b6e9014dd75b1f0f5a143e97b55cccd8f72/src/index.ts#L88

根据代码中数据库操作可知：
需要建立D1，库名：`pastebins` ，还需要建立表 `pastes`
内容为：`id, content, create_time, language, expire, metadata`
其中 `create_time, expire` 这俩是整型，其他为文本

都弄完应该就能用了

**Comment by lirtual** [comment]
> kv_namespaces 没用了，最新的commits已经去掉了 现在数据存在D1里面。 教程也没更新，缺少了对D1设置的说明
> 
> https://github.com/xiadd/pastebin-worker/blob/953d1b6e9014dd75b1f0f5a143e97b55cccd8f72/src/index.ts#L88
> 
> 根据代码中数据库操作可知： 需要建立D1，库名：`pastebins` ，还需要建立表 `pastes` 内容为：`id, content, create_time, language, expire, metadata` 其中 `create_time, expire` 这俩是整型，其他为文本
> 
> 都弄完应该就能用了

原来如此，谢谢你的耐心解答~
